### ISSUE TITLE
Indentation after line wrap

### ISSUE THREAD

**Issue by xwinus** [dcaoyuan/nbscala#128]
Hello,
at first, I'd like to thank you for great plugin for Scala in Netbeans. However, I'm having issue when using *ALT-SHIFT-F* for autoformatting with long sequence of method calls, instead

```scala
val test = foo().foo().foo()
  .bar()
```
(putting two spaces at the beginning of new line), it is formatted like

```scala
val test = foo().foo().foo()
.bar()
```
is this a feature or bug? I didn't find any option in Netbeans formatting settings for Scala for this.
Thanks

**Comment by dcaoyuan** [comment]
Current plugin will use scalariform to format the code. This should have been fixed.
