### ISSUE TITLE
Build with fails after clean clone

### ISSUE THREAD

**Issue by sa1nt** [dcaoyuan/nbscala#152]
After cloning the repo, command `mvn clean install` fails with error 
> [ERROR] Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:3.14:manifest (default-manifest) on project org-netbeans-modules-scala-debugger: Module has friend dependency on org.netbeans.modules.java.preprocessorbridge but is not listed as a friend. -> [Help 1]

Github refused to attach the full maven log of the `mvn clean install` command directly to this issue, so here's a link to [pastebin](http://pastebin.com/x5RbW01w) .

`mvn -version` output
> Apache Maven 3.0.4 (r1232337; 2012-01-17 10:44:56+0200)
> Maven home: C:\apache-maven-3.0.4
> Java version: 1.8.0, vendor: Oracle Corporation
> Java home: C:\Program Files (x86)\Java\jdk1.8.0\jre
> Default locale: en_US, platform encoding: UTF8
> OS name: "windows 7", version: "6.1", arch: "x86", family: "dos"

**Comment by eshikafe** [comment]
Why did you stop development on erlybird? Any reason?

**Comment by sa1nt** [comment]
Closing this since linked pull request #153 was merged into master
