### ISSUE TITLE
Scala Debugger incompatible with latest Netbeans 8.1 update

### ISSUE THREAD

**Issue by thomassuckow** [dcaoyuan/nbscala#156]
Netbeans claims Scala Debugger cannot be installed because of a dependancy on JPDA Debugger UI (Internal to Java Debugger)

Netbeans installs without the latest Java Debugger plugin update just fine.

**Comment by minoleg** [comment]
I have the same issue trying to install the plugin.  Did you figure out the workaround by any chance?

Thanks.

**Comment by thomassuckow** [comment]
Not updating netbeans is the only workaround I know of.

**Comment by dcaoyuan** [comment]
It's a known issue, I'll fix it later.

**Comment by minoleg** [comment]
Thank you, Caoyuan.

**Comment by woshilaiceshide** [comment]
waiting for the fix...

**Comment by oghs** [comment]
@dcaoyuan any suggestion on where to start looking the sources to fix the issue?

**Comment by claydonkey** [comment]
Just wondered what the state of play with nbscala is... Still having to resort to netbeans < 8.1.

**Comment by jfalkner** [comment]
Just hit this error today too. @claydonkey where can I find the older version of the JPDA Debugger. I'm working with a fresh install of NetBeans and plugins.netbeans.org appears to be offline for maintenance.

@dcaoyuan if you point me in the right direction, I'll give a go at putting up a PR with the fix.

**Comment by claydonkey** [comment]
Hi jfalkner 
Have you tried [http://bits.netbeans.org/nexus/content/groups/netbeans/org/netbeans/modules/]
?

**Comment by markkrueger** [comment]
I'm a little confused on the work around mentioned above.  I went to http://bits.netbeans.org/nexus/content/groups/netbeans/org/netbeans/modules/ but it was unclear to me as to exactly what to download in order to change to a old version to work around this issue.
