### ISSUE TITLE
Gitter channel to collaborate 

### ISSUE THREAD

**Issue by prassee** [dcaoyuan/nbscala#180]
I would like to see a gitter channel for this repo so as I can help to exchange feedback , ideas and issues. Its quite prevalent in other IDE communities as well also it helps to get users to try this plugin.

**Comment by Chris2011** [comment]
That would be great of course :)

**Comment by Chris2011** [comment]
@dcaoyuan can you create one please?

**Comment by dcaoyuan** [comment]
Done.

**Comment by Chris2011** [comment]
Great, thx. :)
