### ISSUE TITLE
Can I join the team please?

### ISSUE THREAD

**Issue by mcheung63** [dcaoyuan/nbscala#181]
My name is Peter, email is peter@quantr.hk . Can I join the team please? I love Netbeans and did some netbeans development
http://plugins.netbeans.org/plugin/71031/?show=true
http://plugins.netbeans.org/plugin/60381/?show=true
http://plugins.netbeans.org/plugin/70460/?show=true

**Comment by dcaoyuan** [comment]
Hi @mcheung63 

Feel free to contribute to this project by Pull Request etc.

Cheers,
Caoyuan Deng
