### ISSUE TITLE
The site plugins.netbeans.org is down

### ISSUE THREAD

**Issue by carddamom** [dcaoyuan/nbscala#183]
The plugin website for netbeans is down, it must be Apache taking control of the page... Maybe, you could change the readme.md temporarily...

Also, could you provide a binary in releases?

**Comment by Dirk-c-Walter** [comment]
According to the Apache docs the plugin site is still being used but it has been dead for months.
https://netbeans.apache.org/plugins/index.html

There is also a netbeans 9 release out.

**Comment by carddamom** [comment]
It seems that it's back up...

**Comment by iamumairayub** [comment]
Its down right now again :(

**Comment by davidrochin** [comment]
Down since yesterday

**Comment by BharathASL** [comment]
Again!

Is there any way to download this plugin?
http://plugins.netbeans.org/nbpluginportal/files/nbms/1501524971_nb-darcula-1.6.nbm

**Comment by davidrochin** [comment]
> Again!
> 
> Is there any way to download this plugin?
> http://plugins.netbeans.org/nbpluginportal/files/nbms/1501524971_nb-darcula-1.6.nbm

It seems now it's down forever. It's been down for so long it's not even listen by Google anymore. It's a shame because I can't find anywhere to download the QuickOpener plugin.

**Comment by jasonex7** [comment]
In this page (https://cwiki.apache.org/confluence/display/NETBEANS/Where+to+download+plugins+for+NetBeans+10.0+and+earlier) you can see the URLs for the version of Netbeans you have. 

In my case I use Netbeans 8.2 so I replace "Plugin Portal" repository url for http://plugins.archive.librebeans.org/catalogue/8.2/catalog.xml and it works

**Comment by ebresie** [comment]
As part of migration, the old plugin site managed by Oracle was retired.  Efforts are ongoing to migrate to the new plugin portal

Recommend migrating the plugin to the new plugin.  For additional details see https://cwiki.apache.org/confluence/display/NETBEANS/How+to+get+plugin+on+Plugin+Portal+Update+Center

**Comment by oleg68** [comment]
> In my case I use Netbeans 8.2 so I replace "Plugin Portal" repository url for http://plugins.archive.librebeans.org/catalogue/8.2/catalog.xml and it works

When I'm trying to install a plugin from there I receive an error:

```
Networking problem in http://plugins.archive.librebeans.org/nbms/1482228623_org-netbeans-modules-cnd-debugger-gdbserver.nbm
```

**Comment by Sablam** [comment]
@oleg68 Same as you for gdbserver and clang-tidy.
