### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by quantrpeter** [dcaoyuan/nbscala#188]
Hi
   unable to build by "mvn -DskipTests package"
thanks
<img width="2072" alt="image" src="https://github.com/user-attachments/assets/2c047961-84fb-4a65-9542-fe76ce273aac">

**Comment by rkraneis** [comment]
This project is unfortunately pretty dead. If you check the build requirements in the readme, they talk about Java 8. Using that building should be possible.

**Comment by quantrpeter** [comment]
Thanks @rkraneis . I want to help, but seems kick start the project is hard, it is big.

**Comment by rkraneis** [comment]
@quantrpeter, I think since NetBeans added support for LSP, it may be a better idea to start from scratch and use that.

**Comment by rkraneis** [comment]
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=263425900
