### ISSUE TITLE
Project Window not showing source packages for SBT projects

### ISSUE THREAD

**Issue by berryware** [dcaoyuan/nbscala#80]
The project window is not showing src/main/scala packages and source files for SBT projects. In SBT, the default source directory is src/main/scala. Source packages and files should be listed under projects just like in maven projects. 

![image](https://f.cloud.github.com/assets/231598/313520/a4dd86c0-97b0-11e2-955f-a9876a338f5a.png)

This project is the example project from Odersky's course on Coursera. Here is the build.sbt

========= build.sbt ==================
name <<= submitProjectName(pname => "progfun-"+ pname)

version := "1.0.0"

scalaVersion := "2.10.1"

scalacOptions ++= Seq("-deprecation", "-feature")

libraryDependencies += "org.scalatest" %% "scalatest" % "1.9.1" % "test"

libraryDependencies += "junit" % "junit" % "4.10" % "test"

// This setting defines the project to which a solution is submitted. When creating a
// handout, the 'createHandout' task will make sure that its value is correct.
submitProjectName := "example"

// See documentation in ProgFunBuild.scala
projectDetailsMap := {
val currentCourseId = "progfun-002"
Map(
  "example" ->  ProjectDetails(
                  packageName = "example",
                  assignmentPartId = "fTzFogNl",
                  maxScore = 10d,
                  styleScoreRatio = 0.2,
                  courseId=currentCourseId),
  "recfun" ->     ProjectDetails(
                  packageName = "recfun",
                  assignmentPartId = "3Rarn9Ki",
                  maxScore = 10d,
                  styleScoreRatio = 0.2,
                  courseId=currentCourseId),
  "funsets" ->    ProjectDetails(
                  packageName = "funsets",
                  assignmentPartId = "fBXOL6Qd",
                  maxScore = 10d,
                  styleScoreRatio = 0.2,
                  courseId=currentCourseId),
  "objsets" ->    ProjectDetails(
                  packageName = "objsets",
                  assignmentPartId = "95dMMEz7",
                  maxScore = 10d,
                  styleScoreRatio = 0.2,
                  courseId=currentCourseId),
  "patmat" ->     ProjectDetails(
                  packageName = "patmat",
                  assignmentPartId = "3gPmpcif",
                  maxScore = 10d,
                  styleScoreRatio = 0.2,
                  courseId=currentCourseId),
  "forcomp" ->    ProjectDetails(
                  packageName = "forcomp",
                  assignmentPartId = "fG1oZGIO",
                  maxScore = 10d,
                  styleScoreRatio = 0.2,
                  courseId=currentCourseId),
  "streams" ->    ProjectDetails(
                  packageName = "streams",
                  assignmentPartId = "CWKgCFCi",
                  maxScore = 10d,
                  styleScoreRatio = 0.2,
                  courseId=currentCourseId),
  "simulations" -> ProjectDetails(
                   packageName = "simulations",
                   assignmentPartId = "iYs4GARk",
                   maxScore = 10d,
                   styleScoreRatio = 0.2,
                   courseId="progfun2-001"),
  "interpreter" -> ProjectDetails(
                   packageName = "interpreter",
                   assignmentPartId = "1SZhe1Ut",
                   maxScore = 10d,
                   styleScoreRatio = 0.2,
                   courseId="progfun2-001")
)
}

// Files that we hand out to the students
handoutFiles <<= (baseDirectory, projectDetailsMap, commonSourcePackages) map { (basedir, detailsMap, commonSrcs) =>
  (projectName: String) => {
    val details = detailsMap.getOrElse(projectName, sys.error("Unknown project name: "+ projectName))
    val commonFiles = (PathFinder.empty /: commonSrcs)((files, pkg) =>
      files +++ (basedir / "src" / "main" / "scala" / pkg *\* "_.scala")
    )
    (basedir / "src" / "main" / "scala" / details.packageName *_ "_.scala") +++
    commonFiles +++
    (basedir / "src" / "main" / "resources" / details.packageName *_ "_") +++
    (basedir / "src" / "test" / "scala" / details.packageName *_ "_.scala") +++
    (basedir / "build.sbt") +++
    (basedir / "project" / "build.properties") +++
    (basedir / "project" *_ ("_.scala" || "_.sbt")) +++
    (basedir / "project" / "scalastyle_config.xml") +++
    (basedir / "lib_managed" *\* "*.jar") +++
    (basedir \* (".classpath" || ".project")) +++
    (basedir / ".settings" / "org.scala-ide.sdt.core.prefs")
  }
}

// This setting allows to restrict the source files that are compiled and tested
// to one specific project. It should be either the empty string, in which case all
// projects are included, or one of the project names from the projectDetailsMap.
currentProject := ""

// Packages in src/main/scala that are used in every project. Included in every
// handout, submission.
commonSourcePackages += "common"

// Packages in src/test/scala that are used for grading projects. Always included
// compiling tests, grading a project.
gradingTestPackages += "grading"

========= build.sbt ==================

**Comment by akochnev** [comment]
The NetBeans relies on the nbsbt SBT plugin to be loaded in the project (or in the global settings). The nbsbt plugin generates a hidden .classpath_nb file in the current directory, which is what the NetBeans IDE plugin uses to figure out what source tree to display. 

You will need to add the nbsbt plugin to either project/plugins.sbt, or to your global plugin configuration, e.g. in ~/.sbt/0.13/plugins/plugins.sbt
addSbtPlugin("org.netbeans.nbsbt" % "nbsbt-plugin" % "1.1.2")

When the NetBeans IDE plugin opens the IDE project in a console, it runs the "netbeans" task automatically, which generates the .classpath_nb file. 

The .classpath_nb file contains something like this : 
<classpath name="example" id="assignment">
  <classpathentry kind="src" path="src/main/scala" output="target/scala-2.11/classes" scope="compile" managed="false"/>
  <classpathentry kind="src" path="target/scala-2.11/src_managed/main" output="target/scala-2.11/classes" scope="compile" managed="true"/>
....
</classpath>

I tested this with an example project from coursera, and when the plugin was loaded, after the 'netbeans' task ran, it generated the .classpath_nb file and NetBeans recognized the source roots. 

@dcaoyuan - IMO, this issue can be closed.
