### ISSUE TITLE
mvn build of scala.core fails with error "File name too long"

### ISSUE THREAD

**Issue by bertvv** [dcaoyuan/nbscala#9]
I fetched the [latest revision of the repository](https://github.com/dcaoyuan/nbscala/tree/e13c99620016ac5a48cbfd5e6763b4e251728969) and tried to do a mvn clean install. The compilation of scala.core failed with error message "File name too long" without more information (which file?). Adding -verbose to the scala compiler options reveiled that the error occurs in [ast.ScalaAstVisitor](https://github.com/dcaoyuan/nbscala/blob/e13c99620016ac5a48cbfd5e6763b4e251728969/scala.core/src/main/scala/org/netbeans/modules/scala/core/ast/ScalaAstVisitor.scala): 

```
[...]
[wrote 'ScalaAstVisitor$treeTraverser$$anonfun$org$netbeans$modules$scala$core$ast$ScalaAstVisitor$treeTraverser$$traverse$11' to /home/bert/nbscala/scala.core/target/classes/org/netbeans/modules/scala/core/ast/ScalaAstVisitor$treeTraverser$$anonfun$org$netbeans$modules$scala$core$ast$ScalaAstVisitor$treeTraverser$$traverse$11.class]
error: File name too long
one error found
```

**Comment by csaltos** [comment]
The option -Xmax-classfile-name set to 110 safe my Scala builds agains filename too long. THANKS !! :+1: :smile:
